### ISSUE TITLE
enum comments

### ISSUE THREAD

**Issue by EmperorEarth** [dncrews/GraphQL-SublimeText3#1]
![image](https://cloud.githubusercontent.com/assets/7605016/22175640/140c0b18-dfc7-11e6-993b-5a1d1edc8e9b.png)

Fails to parse comments within Enum blocks as comments

**Comment by dncrews** [comment]
@EmperorEarth: fixed and published in version 1.4.0

**Comment by EmperorEarth** [comment]
Thanks @dncrews
