### ISSUE TITLE
Update syntax

### ISSUE THREAD

**Issue by Thom1729** [dncrews/GraphQL-SublimeText3#7]
I'd be interested in updating and expanding the syntax to:

- Include queries, mutations, and so on
- Provide more detailed meta scopes.
- Remove the lookbehinds (which are bad for performance because they force Oniguruma instead of the new, faster regexp engine).
- Use the symbol list (i.e. ctrl-R).
- As appropriate, update scopes to the current standard conventions.
- Add comprehensive test coverage.

This would involve a significant restructuring of the current syntax. Does this seem like a worthwhile change? Are there any specific concerns that should be addressed as part of such a project?

**Comment by Thom1729** [comment]
@dncrews @fermads Any thoughts? I've just started a job where I'm working with GraphQL, and I'd like to get started on this.

**Comment by dncrews** [comment]
Seems fine by me.
